# Generated by Django 4.0 on 2023-12-08 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='dislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliker', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='expansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_link', models.URLField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('max_player', models.IntegerField()),
                ('min_player', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_link', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('max_player', models.IntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('min_player', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='teaming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliker', models.TextField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=60)),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created', to='auth.user')),
                ('editer', models.ManyToManyField(blank=True, related_name='editer', to=settings.AUTH_USER_MODEL)),
                ('expansions', models.ManyToManyField(blank=True, related_name='expansions', to='modelclasses.expansion')),
                ('game', models.ManyToManyField(blank=True, through='modelclasses.dislikes', to='modelclasses.game')),
                ('viewer', models.ManyToManyField(blank=True, related_name='viewer', to=settings.AUTH_USER_MODEL)),
                ('wishlist_expansions', models.ManyToManyField(blank=True, related_name='wishlist_expansions', to='modelclasses.expansion')),
                ('wishlist_games', models.ManyToManyField(blank=True, related_name='wishlist_games', to='modelclasses.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='modelclasses.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='teaming',
            field=models.ManyToManyField(blank=True, to='modelclasses.teaming'),
        ),
        migrations.AddField(
            model_name='expansion',
            name='base_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelclasses.game'),
        ),
        migrations.AddField(
            model_name='expansion',
            name='teaming',
            field=models.ManyToManyField(blank=True, default=None, to='modelclasses.teaming'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelclasses.game'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelclasses.location'),
        ),
    ]
