# Generated by Django 5.0 on 2023-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='genre',
            field=models.ManyToManyField(blank=True, to='modelclasses.genre'),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='teaming',
            field=models.ManyToManyField(blank=True, to='modelclasses.teaming'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, to='modelclasses.genre'),
        ),
    ]
