# Generated by Django 5.0 on 2023-12-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclasses', '0002_expansion_genre_alter_expansion_teaming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansion',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='rule_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
