# Generated by Django 5.0 on 2023-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclasses', '0003_alter_expansion_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansion',
            name='duration',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
